### PR TITLE
Fewer allocations by making function signatures take `&CStr`s.

### PR DESCRIPTION
**Pull request by frewsxcv**
As discussed in https://github.com/tildeio/helix/pull/76.

[breaking-change]

### CODE REVIEW

**Comment by chancancode** [comment]
Seems good to me, but I am a bit surprised that it didn't break any tests: wouldn't we need to change the caller (in the macros) for this to work correctly? Or are &str and &CStr somehow compatible so it Just Works™?

**Comment by frewsxcv** [comment]
I just checked, and it looks like none of this code is used anywhere. The macros seem to be calling the unsafe bindings via `ClassDefinition::define_method`.

It seems like there should unsafe bindings for ruby (which seems to be libcruby_sys), safe idiomatic rust bindings built on top of that (which is a bit scattered currently)  (maybe should be called libcruby), and everything else should be built on top of that (mainly the macros)

**Comment by chancancode** [comment]
The macros use define_method (which you changed on L78), so I thought they would need to be updated to pass a CStr, but everything is still working according to CI, which is what puzzles me.

FWIW, the structure you described is _roughly_ what is going on here. The lowest level is sys::rb_define_method which is called from L38 and L51. The APIs you changed here is more or less the "safe" Rust bindings, and the macros are "built on top", in a way. They could definitely be better organized/rationalized, for sure.

**Comment by frewsxcv** [comment]
> The macros use define_method (which you changed on L78), so I thought they would need to be updated to pass a CStr, but everything is still working according to CI, which is what puzzles me.

presumably, [here's an example of a macro you're talking about](https://github.com/tildeio/helix/blob/be453117bf2be1a78ea7434dcb3d804854379312/src/macros/init.rs#L224). the method being called is [`ClassDefinition::define_method`](https://github.com/tildeio/helix/blob/be453117bf2be1a78ea7434dcb3d804854379312/src/class_definition.rs#L49-L72) (what I mentioned in my previous comment) which is different from the method changed in this PR

**Comment by chancancode** [comment]
ahhhhh I totally misunderstood you. That makes sense now. So this seems fine to merge but tbh if these are unused we can probably just delete them ¯\_(ツ)_/¯

**Comment by chancancode** [comment]
Thank you @frewsxcv!

**Pull request merged**
