### PR TITLE
Expose `RB_NIL_P` and `RTEST` in libcruby

### PR DESCRIPTION
**Pull request by sgrif**
These seem to be the appropriate way to check for `nil` and truthiness
of an object using the C API. I would assume that additional changes
have to happen since this touches the runtime extension, but I'm not
sure what to do.

### CODE REVIEW

**Comment by wycats** [comment]
Can you add tests in https://github.com/tildeio/helix/blob/master/ruby/spec/helix_runtime_spec.rb. You should be able to follow the patterns for similar functions. You will probably need to modify the dummy C extension, which is used to expose test-specific functionality.

**Comment by sgrif** [comment]
Rebased and added tests.

**Comment by sgrif** [comment]
I'm unsure why the windows tests are failing CI. It looks like you might have some appveyor settings that require a manual rebuild of the C lib? I could use some help getting this green

**Comment by sgrif** [comment]
CI is green on this FYI

**Comment by wycats** [comment]
@sgrif thx!

**Pull request merged**
