### PR TITLE
Export another smattering of random functions/constants

### PR DESCRIPTION
**Pull request by sgrif**

### CODE REVIEW

**Comment by sgrif** [comment]
Is there anything else I need to do on this?

**Comment by JordiPolo** [comment]
@wycats will this get merged after @sgrif fixes conflicts?

**Comment by wycats** [comment]
@JordiPolo yep

**Comment by sgrif** [comment]
Wasn't aware there were conflicts, sorry. I've rebased and fixed the conflicts.

**Comment by wycats** [comment]
@JordiPolo @sgrif merged!

**Pull request merged**
